# Nombre de la aplicación Spring Boot
spring.application.name=${SPRING_APPLICATION_NAME}

# Configuración de la base de datos PostgreSQL
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Mostrar sentencias SQL en la consola
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

# Actualizar la base de datos y crear entidades automáticamente
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

# Configuración específica de Hibernate para PostgreSQL
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

# Configuración para habilitar/deshabilitar Swagger UI y API docs
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED}
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH}

# Configuración de límites de tamaño para subida de archivos
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}
media.location=${MEDIA_LOCATION}

# Configuración para el envío de correo usando Gmail SMTP
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.timeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT}

# Configuración para Spring DevTools
spring.devtools.restart.enabled=${SPRING_DEVTOOLS_RESTART_ENABLED}

# Ejemplo de comentarios adicionales sobre la documentación de Swagger y credenciales
# Correo gmail:iapex6500@gmail.com
# Contraseña gmail:ljQbs(JOab%9jY1Q
# DOCUMENTACION SWAGGER http://localhost:8080/swagger-ui/index.html#/authentication-controller/register
# j4!!MhZ_VexjcJ7
